# # official tutorial 
# # mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# # mkdocs: https://www.mkdocs.org/user-guide/configuration/

# site_name: Climate Philanthropy
# theme:
#   name: material
#   #  favicon: attachment/portrait.png
#   language: en
#   features:
#     - navigation.expand 
#     - tabs 
# markdown_extensions: 
#   - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
#   - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
#   - nl2br # newline-to-break 
#   - toc:
#       permalink: '#' # heading anchor 
#       slugify: !!python/name:pymdownx.slugs.uslugify # 解决中文标题解析问题
#   - admonition
#   - codehilite:
#       guess_lang: false
#       linenums: false
#   - footnotes
#   - meta
#   - def_list
#   - pymdownx.arithmatex
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.critic
#   - pymdownx.details
#   # - pymdownx.emoji:
#       # emoji_generator: !!python/name:pymdownx.emoji.to_png
#   - pymdownx.inlinehilite
#   - pymdownx.magiclink
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.superfences
#   - pymdownx.tasklist
#   - pymdownx.tilde
# plugins:
#   - search
#   - roamlinks 
#     #- autolinks 
#   - exclude:
#       glob:
#         - "*.tmp"
#         - "*.pdf"
#         - "*.gz"
#       regex:
#         - '.*\.(tmp|bin|tar)$'
name: ci 


on:
  push:
    branches:
      - master 


      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 


      - run: mkdocs gh-deploy --force