# name: ci 

# on:
#   push:
#     branches:
#       - master 
#       - main
#   workflow_dispatch:
# permissions:
#   contents: write
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Configure Git Credentials
#         run: |
#           git config user.name github-actions[bot]
#           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
#       - uses: actions/setup-python@v5
#         with:
#           python-version: 3.x
#       - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
#       - uses: actions/cache@v4
#         with:
#           key: mkdocs-material-${{ env.cache_id }}
#           path: .cache
#           restore-keys: |
#             mkdocs-material-
#       - run: pip install mkdocs-material 
#       - run: pip install mkdocs-exclude
#       - run: pip install mkdocs-roamlinks-plugin
#       - run: mkdocs gh-deploy --force

# From: [Site works on local (mkdocs serve) but not when published on GitHub. · mkdocs/mkdocs · Discussion #3432 · GitHub](https://github.com/mkdocs/mkdocs/discussions/3432)

name: Build and deploy

on:
  workflow_dispatch: # Allow manual triggers
  push:
    tags-ignore:
      - '**' # Ignore any tags here
    branches:
      - main
      - master
    #
    # Trigger when either files in the docs folder,
    # the requirements.txt file or the mkdocs.yml file
    # are edited and commited.
    paths:
      - 'docs/**'
      - 'requirements.txt'
      - 'mkdocs.yml'

# These permissions are required for it to work
permissions:
  contents: read
  pages: write
  id-token: write

# Makes sure only one workflow runs at a time.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.x
        uses: actions/setup-python@v5

        with:
          python-version: 3.x
      - name: Install dependencies
        # Alternatively: pip install mkdocs
        run: pip install -r requirements.txt
      - name: Build Docs
        run: mkdocs build
      - name: Configure GitHub Pages
        # I have no idea if this actually needed...
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'site/' # MkDocs builds to site/ by default

      - name: Deploy to GitHub Pages
        id: deployment # This is required for environment
        uses: actions/deploy-pages@v2